name = "day_02"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Thierry Rascle"]
maintainers = ["Thierry Rascle <thierr26@free.fr>"]
maintainers-logins = ["thierr26"]

executables = ["day_02"]
